version: '2'
services:
    jhipsterexample-app:
        image: jhipsterexample
        external_links:
            - jhipsterexample-mysql:mysql
            - jhipsterexample-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://46.219.112.90:3306/jhipsterexample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterexample-mysql:
        extends:
            file: mysql.yml
            service: jhipsterexample-mysql
    jhipsterexample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterexample-elasticsearch
